Udate to 3.6.2
**Changelog:**

- - Pinned Trio to < 0.22 to avoid incompatibility with AnyIO's `ExceptionGroup` class causing `AttributeError: 'NonBaseMultiError' object has no attribute '_exceptions'`

Signed-off-by: Algent Albrahimi <algent@protonmail.com>